In [328]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, KFold
from sklearn.preprocessing import StandardScaler
from sklearn import preprocessing, svm
import matplotlib.pyplot as plt
import math
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor
scaler = StandardScaler()

In [47]:
X_full = pd.read_csv(r"C:\Users\wille\Documents\AppliedStats\Project\CleanData\X.csv")
X_full = scaler.fit_transform(X_full)
X_violent = pd.read_csv(r"C:\Users\wille\Documents\AppliedStats\Project\Vars\X_refined_violent.csv", index_col=0).values
X_n_violent = pd.read_csv(r"C:\Users\wille\Documents\AppliedStats\Project\Vars\X_refined_n_violent.csv", index_col=0).values
Y = pd.read_csv(r"C:\Users\wille\Documents\AppliedStats\Project\Vars\Y.csv", index_col = 0)
target_violent = Y.Total_Violent.values
target_n_violent = Y["Non.Violent"].values

In [41]:
k_folds = 10
kf = KFold(n_splits=k_folds, shuffle=True, random_state=42)

rf_model = RandomForestRegressor(n_estimators=100, random_state=42)

mse_scores = []

# Perform k-fold cross-validation
for train_index, test_index in kf.split(X_full):
    X_train, X_test = X_full[train_index], X_full[test_index]
    y_train, y_test = target_violent[train_index], target_violent[test_index]

    # Fit the Random Forest model on the training data
    rf_model.fit(X_train, y_train)

    # Make predictions on the test data
    y_pred = rf_model.predict(X_test)

    # Calculate MSE and store it
    mse = mean_squared_error(y_test, y_pred)
    mse_scores.append(mse)

# Calculate the average MSE across all folds
rf_fv = np.sqrt(np.mean(mse_scores))

In [51]:
rf_fv

378.39971717541965

In [94]:
mse_scores = []
rf_model = RandomForestRegressor(n_estimators=200,max_features = 'log2')


for train_index, test_index in kf.split(X_violent):
    print(train_index)
    X_train, X_test = X_violent[train_index], X_violent[test_index]
    y_train, y_test = target_violent[train_index], target_violent[test_index]

    # Fit the Random Forest model on the training data
    rf_model.fit(X_train, y_train)

    # Make predictions on the test data
    y_pred = rf_model.predict(X_test)

    # Calculate accuracy and store it
    mse = mean_squared_error(y_test, y_pred)
    mse_scores.append(mse)

# Calculate the average accuracy across all folds
rf_rv = np.sqrt(np.mean(mse_scores))

[   0    3    4 ... 2212 2213 2214]
[   0    1    2 ... 2212 2213 2214]
[   0    1    2 ... 2211 2212 2214]
[   0    1    2 ... 2211 2212 2213]
[   0    1    2 ... 2211 2213 2214]
[   0    1    2 ... 2212 2213 2214]
[   0    1    2 ... 2212 2213 2214]
[   0    1    2 ... 2212 2213 2214]
[   1    2    3 ... 2212 2213 2214]
[   0    1    2 ... 2212 2213 2214]


In [95]:
rf_rv

366.4523611644714

In [98]:
from xgboost import XGBRegressor

In [289]:
learning_rate = 0.1
num_estimators = 20000

bst = XGBRegressor(
    objective='reg:squarederror',
    learning_rate=learning_rate,
    n_estimators=num_estimators,
    max_depth = 5
)

k_folds = 10
kf = KFold(n_splits=k_folds, shuffle=True)

mse_scores = []

# Perform k-fold cross-validation
for train_index, test_index in kf.split(X_full):
    X_train, X_test = X_full[train_index], X_full[test_index]
    y_train, y_test = target_violent[train_index], target_violent[test_index]

    # Fit the Random Forest model on the training data
    bst.fit(X_train, y_train)

    # Make predictions on the test data
    y_pred = bst.predict(X_test)

    # Calculate MSE and store it
    mse = mean_squared_error(y_test, y_pred)
    mse_scores.append(mse)

# Calculate the average MSE across all folds
bst_rv = np.sqrt(np.mean(mse_scores))

In [290]:
bst_rv

378.28901811910174

In [183]:
from lightgbm import LGBMRegressor

In [326]:
k_folds = 10
kf = KFold(n_splits=k_folds, shuffle=True)
lgm = LGBMRegressor(boosting_type='gbdt',
                   num_leaves=17,
                   learning_rate = 0.1,
                   n_estimators=100,
                   verbose=0)
mse_scores = []

# Perform k-fold cross-validation
for train_index, test_index in kf.split(X_full):
    X_train, X_test = X_full[train_index], X_full[test_index]
    y_train, y_test = target_violent[train_index], target_violent[test_index]

    # Fit the Random Forest model on the training data
    lgm.fit(X_train, y_train)

    # Make predictions on the test data
    y_pred = lgm.predict(X_test)

    # Calculate MSE and store it
    mse = mean_squared_error(y_test, y_pred)
    mse_scores.append(mse)

# Calculate the average MSE across all folds
lgm_rv = np.sqrt(np.mean(mse_scores))

In [327]:
lgm_rv

370.7586193420597

In [352]:
mse_scores = []
ada = AdaBoostRegressor(learning_rate = 0.07, n_estimators = 40)

# Perform k-fold cross-validation
for train_index, test_index in kf.split(X_violent):
    X_train, X_test = X_violent[train_index], X_violent[test_index]
    y_train, y_test = target_violent[train_index], target_violent[test_index]

    # Fit the Random Forest model on the training data
    ada.fit(X_train, y_train)

    # Make predictions on the test data
    y_pred = ada.predict(X_test)

    # Calculate MSE and store it
    mse = mean_squared_error(y_test, y_pred)
    mse_scores.append(mse)

# Calculate the average MSE across all folds
ada_rv = np.sqrt(np.mean(mse_scores))

In [353]:
ada_rv

394.7626900382202

Non-Violent Crimes

In [378]:
k_folds = 10
kf = KFold(n_splits=k_folds, shuffle=True)

rf_model = RandomForestRegressor(n_estimators=400, max_features = 'sqrt', max_depth = 20)
mse_scores = []

# Perform k-fold cross-validation
for train_index, test_index in kf.split(X_n_violent):
    X_train, X_test = X_n_violent[train_index], X_n_violent[test_index]
    y_train, y_test = target_n_violent[train_index], target_n_violent[test_index]

    # Fit the Random Forest model on the training data
    rf_model.fit(X_train, y_train)

    # Make predictions on the test data
    y_pred = rf_model.predict(X_test)

    # Calculate MSE and store it
    mse = mean_squared_error(y_test, y_pred)
    mse_scores.append(mse)

# Calculate the average MSE across all folds
rf_fv = np.sqrt(np.mean(mse_scores))

In [379]:
rf_fv

1875.372560786954

In [384]:
learning_rate = 0.05
num_estimators = 4000

bst = XGBRegressor(
    objective='reg:squarederror',
    learning_rate=learning_rate,
    n_estimators=num_estimators,
    max_depth = 5
)

k_folds = 10
kf = KFold(n_splits=k_folds, shuffle=True)

mse_scores = []

# Perform k-fold cross-validation
for train_index, test_index in kf.split(X_n_violent):
    X_train, X_test = X_n_violent[train_index], X_n_violent[test_index]
    y_train, y_test = target_n_violent[train_index], target_n_violent[test_index]

    # Fit the Random Forest model on the training data
    bst.fit(X_train, y_train)

    # Make predictions on the test data
    y_pred = bst.predict(X_test)

    # Calculate MSE and store it
    mse = mean_squared_error(y_test, y_pred)
    mse_scores.append(mse)

# Calculate the average MSE across all folds
bst_rv = np.sqrt(np.mean(mse_scores))

In [385]:
bst_rv

1918.4830681913486

In [388]:
k_folds = 10
kf = KFold(n_splits=k_folds, shuffle=True)
lgm = LGBMRegressor(boosting_type='gbdt',
                   num_leaves=17,
                   learning_rate = 0.1,
                   n_estimators=100,
                   verbose=0)
mse_scores = []

# Perform k-fold cross-validation
for train_index, test_index in kf.split(X_n_violent):
    X_train, X_test = X_n_violent[train_index], X_n_violent[test_index]
    y_train, y_test = target_n_violent[train_index], target_n_violent[test_index]

    # Fit the Random Forest model on the training data
    lgm.fit(X_train, y_train)

    # Make predictions on the test data
    y_pred = lgm.predict(X_test)

    # Calculate MSE and store it
    mse = mean_squared_error(y_test, y_pred)
    mse_scores.append(mse)

# Calculate the average MSE across all folds
lgm_rv = np.sqrt(np.mean(mse_scores))

In [389]:
lgm_rv

1880.1056933011275